[versions]
kotlin = "1.9.22"
compose = "1.6.0-beta02"
compose-plugin = "1.5.8"
npm-publish = "3.4.2"
kilua = "0.0.1"
kotlinx-atomicfu = "0.23.1"
kotlinx-coroutines = "1.8.0-RC2"
kotlinx-serialization = "1.6.2"
kotlinx-datetime = "0.5.0"
detekt = "1.23.4"
vannik-maven-publish = "0.25.3"
npm-kilua-assets = "0.0.5"
css-loader = "6.8.1"
style-loader = "3.3.3"
imports-loader = "4.0.1"
splitjs = "1.6.5"
html-differ = "1.4.0"
popperjs-core = "2.11.8"
bootstrap = "5.3.2"
bootstrap-icons = "1.11.3"
fontawesome = "6.5.1"
trix = "2.0.10"
toastify = "1.12.0"
tempus-dominus = "6.9.5"
tom-select = "2.3.1"
imask = "7.3.0"

[libraries]
kotlinx-atomicfu = { module = "org.jetbrains.kotlinx:atomicfu", version.ref = "kotlinx-atomicfu" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }

[plugins]
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
npm-publish = { id = "dev.petuska.npm.publish", version.ref = "npm-publish" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "vannik-maven-publish" }
