[versions]
kilua = "0.0.7"
kilua-published = "0.0.7"
kotlin = "2.0.0"
compose = "1.6.11"
dokka = "1.9.20"
nmcp = "0.0.8"
ksp = "2.0.0-1.0.22"
detekt = "1.23.6"
npm-publish = "3.4.2"
gradle-plugin-publish = "1.2.1"
kilua-rpc = "0.0.13"
kilua-gettext = "0.0.2"
kotlinx-atomicfu = "0.25.0"
kotlinx-coroutines = "1.9.0-RC"
kotlinx-serialization = "1.7.1"
kotlinx-datetime = "0.6.0"
javalin = "6.1.6"
jooby = "3.2.3"
ktor = "2.3.12"
koin = "3.6.0-Beta4"
koin-annotations = "1.3.1"
micronaut = "4.5.0"
micronaut-plugins = "4.4.0"
spring-boot = "3.3.1"
spring-dependency-management = "1.1.5"
vertx = "4.5.8"
vertx-plugin = "1.4.0"
ballast = "4.2.1"
shadow = "8.1.1"
logback = "1.5.6"
tomlj = "1.1.1"
resources-optimizer = "2.6.4"
expiring-map = "0.5.11"
npm-kilua-assets = "0.0.12"
css-loader = "7.1.2"
style-loader = "4.0.0"
imports-loader = "5.0.0"
splitjs = "1.6.5"
html-differ = "1.4.0"
popperjs-core = "2.11.8"
bootstrap = "5.3.3"
bootstrap-icons = "1.11.3"
fontawesome = "6.5.2"
trix = "2.1.1"
toastify = "1.12.0"
tempus-dominus = "6.9.9"
tom-select = "2.3.1"
imask = "7.6.1"
tabulator = "6.2.1"
rsup-progress = "3.2.0"
lz-string = "1.5.0"
marked = "13.0.2"
sanitize-html = "2.13.0"
postcss = "8.4.39"
postcss-loader = "8.1.1"
autoprefixer = "10.4.19"
tailwindcss = "3.4.4"
cssnano = "7.0.3"
mini-css-extract-plugin = "2.9.0"

[libraries]
kotlinx-atomicfu = { module = "org.jetbrains.kotlinx:atomicfu", version.ref = "kotlinx-atomicfu" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-reactor = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-reactor", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
ksp-symbol-processing-api = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }
ksp-gradle-plugin = { module = "com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
javalin = { module = "io.javalin:javalin", version.ref = "javalin" }
jooby-kotlin = { module = "io.jooby:jooby-kotlin", version.ref = "jooby" }
jooby-netty = { module = "io.jooby:jooby-netty", version.ref = "jooby" }
kilua-rpc-core = { module = "dev.kilua:kilua-rpc-core", version.ref = "kilua-rpc" }
kilua-rpc-ktor-koin = { module = "dev.kilua:kilua-rpc-ktor-koin", version.ref = "kilua-rpc" }
ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
ktor-server-netty = { module = "io.ktor:ktor-server-netty", version.ref = "ktor" }
ktor-server-compression = { module = "io.ktor:ktor-server-compression", version.ref = "ktor" }
ktor-server-caching-headers = { module = "io.ktor:ktor-server-caching-headers", version.ref = "ktor" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-annotations = { module = "io.insert-koin:koin-annotations", version.ref = "koin-annotations" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
micronaut-platform = { module = "io.micronaut.platform:micronaut-platform", version.ref = "micronaut" }
spring-boot-starter = { module = "org.springframework.boot:spring-boot-starter", version.ref = "spring-boot" }
spring-boot-starter-webflux = { module = "org.springframework.boot:spring-boot-starter-webflux", version.ref = "spring-boot" }
vertx-web = { module = "io.vertx:vertx-web", version.ref = "vertx" }
vertx-lang-kotlin = { module = "io.vertx:vertx-lang-kotlin", version.ref = "vertx" }
vertx-lang-kotlin-coroutines = { module = "io.vertx:vertx-lang-kotlin-coroutines", version.ref = "vertx" }
ballast-core = { module = "io.github.copper-leaf:ballast-core", version.ref = "ballast" }
ballast-saved-state = { module = "io.github.copper-leaf:ballast-saved-state", version.ref = "ballast" }
ballast-repository = { module = "io.github.copper-leaf:ballast-repository", version.ref = "ballast" }
ballast-sync = { module = "io.github.copper-leaf:ballast-sync", version.ref = "ballast" }
ballast-undo = { module = "io.github.copper-leaf:ballast-undo", version.ref = "ballast" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
tomlj = { module = "org.tomlj:tomlj", version.ref = "tomlj" }
resources-optimizer = { module = "org.primefaces.extensions:resources-optimizer-maven-plugin", version.ref = "resources-optimizer" }
expiring-map = { module = "net.jodah:expiringmap", version.ref = "expiring-map" }
kilua-gettext = { module = "dev.kilua:kilua-gettext", version.ref = "kilua-gettext" }
compose-gradle-plugin = { module = "org.jetbrains.compose:compose-gradle-plugin", version.ref = "compose" }

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
npm-publish = { id = "dev.petuska.npm.publish", version.ref = "npm-publish" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
nmcp = { id = "com.gradleup.nmcp", version.ref = "nmcp" }
kilua-rpc = { id = "dev.kilua.rpc", version.ref = "kilua-rpc" }
gradle-plugin-publish = { id = "com.gradle.plugin-publish", version.ref = "gradle-plugin-publish" }
kilua = { id = "dev.kilua", version.ref = "kilua-published" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
jooby = { id = "io.jooby.run", version.ref = "jooby" }
vertx = { id = "io.vertx.vertx-plugin", version.ref = "vertx-plugin" }
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
micronaut-application = { id = "io.micronaut.application", version.ref = "micronaut-plugins" }
micronaut-aot = { id = "io.micronaut.aot", version.ref = "micronaut-plugins" }
