[versions]
kotlin = "1.9.21"
compose = "1.5.10-dev-wasm03"
compose-plugin = "1.5.4"
npm-publish = "3.4.1"
kilua = "0.0.1"
kotlinx-coroutines = "1.7.2-wasm3"
kotlinx-serialization = "1.6.2"
kotlinx-datetime = "0.4.1-wasm1"
detekt = "1.23.3"
vannik-maven-publish = "0.25.3"
npm-kilua-assets = "0.0.9"
css-loader = "6.8.1"
style-loader = "3.3.3"
imports-loader = "4.0.1"
splitjs = "1.6.5"
html-differ = "1.4.0"
popperjs-core = "2.11.8"
bootstrap = "5.3.2"
bootstrap-icons = "1.11.0"
trix = "2.0.8"

[libraries]
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }

[plugins]
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
npm-publish = { id = "dev.petuska.npm.publish", version.ref = "npm-publish" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "vannik-maven-publish" }
